use_frameworks!

target 'podTest_Example' do
  pod 'podTest', :path => '../'

  target 'podTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
